//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StardewValleyCalculator.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StardewValleyCalculator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Blue Jazz	Spring	30	P	50	P	7	
        ///Cauliflower	Spring	80	P	175	P	12	
        ///Garlic	Spring	40	P	60		4	
        ///Green Bean	Spring	60	P	40	P	10	3
        ///Kale	Spring	70	P	110	P	6	
        ///Parsnip	Spring	20	P	35	P	4	
        ///Potato	Spring	50	P	96	P	6	
        ///Rhubarb	Spring	100	D	220		13	
        ///Strawberry	Spring	100	P	120	P	8	4
        ///Tulip	Spring	20	P	30		6	
        ///Blueberry	Summer	80	P	280		14	4
        ///Hops	Summer	60	P	25		11	1
        ///Hot Pepper	Summer	40		40		5	3
        ///Melon	Summer	80		250		12	
        ///Peppers	Summer	40	P	40		5	3
        ///Poppy	Summer	100	P	140		7	
        ///Radish	Summer	40	P	90		6	
        ///Red Cab [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Crops {
            get {
                return ResourceManager.GetString("Crops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Amaranth	50	20
        ///Blueberry	25	10
        ///Cauliflower	75	30
        ///Corn	25	10
        ///Cranberry	38	15
        ///Eggplant	20	8
        ///Green Bean	25	10
        ///Hops	45	18
        ///Jazz	45	18
        ///Kale	50	20
        ///Melon	113	45
        ///Parsnip	25	10
        ///Peppers	13	5
        ///Poppy	45	18
        ///Potato	25	10
        ///Pumpkin	0	0
        ///Radish	45	18
        ///Red Cabbage	75	30
        ///Spangle	45	18
        ///Starfruit	125	50
        ///Tomato	20	8
        ///Wheat	0	0 的當地語系化字串。
        /// </summary>
        internal static string EnergyAndHealths {
            get {
                return ResourceManager.GetString("EnergyAndHealths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 
        ///xnbData: 
        ///    target: &quot;w&quot;
        ///    compressed: true
        ///    hiDef: true
        ///    readerData: 
        ///        - 
        ///            type: &quot;Microsoft.Xna.Framework.Content.DictionaryReader`2[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]&quot;
        ///            version: 0
        ///
        ///        - 
        ///            type: &quot;Microsoft.Xna.Framework.Content.Int32Reader&quot;
        ///            version: 0
        ///
        ///        - 
        ///            type: &quot;Microsoft. [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Fish {
            get {
                return ResourceManager.GetString("Fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 
        ///xnbData: 
        ///    target: &quot;w&quot;
        ///    compressed: true
        ///    hiDef: true
        ///    readerData: 
        ///        - 
        ///            type: &quot;Microsoft.Xna.Framework.Content.DictionaryReader`2[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]&quot;
        ///            version: 0
        ///
        ///        - 
        ///            type: &quot;Microsoft.Xna.Framework.Content.StringReader&quot;
        ///            version: 0
        ///
        ///
        ///    numSharedResources: 0
        ///
        ///content:   [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
    }
}
